### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by felipefrocha** [Pluralith/pluralith-linux-installer#3]
Try to run installer, but got this error.

If there are pre-requirements, could you list them?

```bash
./pluralith_linux_installer_amd64_0.1.1: error while loading shared libraries: libEGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by DanThePutzer** [comment]
Hi @felipefrocha,

We haven't run into this before and weren't aware this was a dependency. The linux installer uses a Golang UI framework called Gio, seems like Gio has that dependency need. During our testing (mostly on Ubuntu) it seems like `libegl` was always present by default, which distro are you using?

On the [Gio website](https://gioui.org/doc/install/linux) the following dependencies are listed as dev dependencies, `libegl` is one of them:
```sh
apt install gcc pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev libvulkan-dev
```
Oddly, it looks like production builds still needs some of those too.

Were you able to get it to run after installing `libegl`?

Cheers,
Dan

**Comment by felipefrocha** [comment]
Hi @DanThePutzer 
It was a docker image from ubuntu:20.04
Thanks for the tip it works

**Comment by DanThePutzer** [comment]
Awesome man! Let me know what you think of the output 👌
