### ISSUE TITLE
Requires FUSE to run

### ISSUE THREAD

**Issue by jamesearl** [Pluralith/pluralith-linux-installer#4]
Dropping a note for future travelers that this depends on `libfuse-dev`. So if you try to run the appImage and see an error like this one:

```
$ ./Pluralith.AppImage
dlopen(): error loading libfuse.so.2

AppImages require FUSE to run. 
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
```

Then your fix is something like this, depending on your OS (mine being Ubuntu 22.04):
```
sudo apt install libfuse-dev
```

**Comment by DanThePutzer** [comment]
Hi @jamesearl 

Thanks for the heads up! I'll keep this issue open so people have an easier time finding it!

How did Pluralith run for you overall and how are the diagrams? Always great to hear what people think :)

**Comment by DanThePutzer** [comment]
Significant changes to how Pluralith runs locally make the Linux installer obsolete.
